/**
 * Seed data for testing and development
 */

import type { Application, Company, Contact, Document, Interview } from '@/types';
import { db } from './db';
import { generateId } from './utils';

export async function seedDatabase() {
  // Check if already seeded
  const existingApplications = await db.applications.count();
  if (existingApplications > 0) {
    return;
  }

  const sampleApplications: Omit<Application, 'id' | 'createdAt' | 'updatedAt'>[] = [
    {
      companyName: 'TechCorp Inc',
      position: 'Senior Frontend Developer',
      status: 'interviewing',
      priority: 'high',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'San Francisco, CA',
      salary: {
        min: 120000,
        max: 160000,
        currency: 'USD',
      },
      jobUrl: 'https://techcorp.com/jobs/123',
      appliedDate: new Date('2024-01-15'),
      targetDate: new Date('2024-01-10'),
      tags: ['react', 'typescript', 'remote'],
      notes: 'Really excited about this opportunity. Contacted recruiter.',
    },
    {
      companyName: 'StartupXYZ',
      position: 'Full Stack Engineer',
      status: 'interviewing',
      priority: 'medium',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'New York, NY',
      salary: {
        min: 100000,
        max: 140000,
        currency: 'USD',
      },
      appliedDate: new Date('2024-01-20'),
      targetDate: new Date('2024-01-18'),
      tags: ['node', 'react', 'mongodb'],
    },
    {
      companyName: 'BigTech Solutions',
      position: 'React Developer',
      status: 'offer',
      priority: 'high',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Seattle, WA',
      salary: {
        min: 150000,
        max: 180000,
        currency: 'USD',
      },
      appliedDate: new Date('2024-01-05'),
      targetDate: new Date('2024-01-01'),
      offerDate: new Date('2024-01-25'),
      responseDeadline: new Date('2024-02-05'),
      tags: ['react', 'redux', 'graphql'],
      notes: 'Received offer! Need to respond by Feb 5th.',
    },
    {
      companyName: 'CloudScale Systems',
      position: 'Software Engineer',
      status: 'interviewing',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Austin, TX',
      appliedDate: new Date('2025-10-28'),
      targetDate: new Date('2025-10-25'),
      tags: ['aws', 'microservices'],
      notes: 'Excited about the cloud infrastructure focus.',
    },
    {
      companyName: 'DataDriven Co',
      position: 'Frontend Architect',
      status: 'rejected',
      priority: 'low',
      workType: 'hybrid',
      employmentType: 'contract',
      location: 'Boston, MA',
      salary: {
        min: 90,
        max: 120,
        currency: 'USD',
      },
      appliedDate: new Date('2024-01-10'),
      targetDate: new Date('2024-01-08'),
      tags: ['angular', 'rxjs'],
    },
    {
      companyName: 'InnovateLabs',
      position: 'UI/UX Engineer',
      status: 'interviewing',
      priority: 'high',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      appliedDate: new Date('2025-10-20'),
      targetDate: new Date('2025-10-18'),
      tags: ['design-systems', 'react', 'figma'],
      notes: 'Dream company! Excited about the interview.',
    },
    {
      companyName: 'FinTech Innovators',
      position: 'JavaScript Developer',
      status: 'accepted',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Chicago, IL',
      salary: {
        min: 130000,
        max: 150000,
        currency: 'USD',
      },
      appliedDate: new Date('2023-12-20'),
      offerDate: new Date('2024-01-15'),
      tags: ['typescript', 'vue', 'jest'],
      notes: 'Accepted offer! Start date Feb 15th.',
    },
    {
      companyName: 'Mobile First Inc',
      position: 'React Native Developer',
      status: 'withdrawn',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Los Angeles, CA',
      appliedDate: new Date('2024-01-08'),
      targetDate: new Date('2024-01-05'),
      tags: ['react-native', 'mobile'],
      notes: 'Withdrew application - accepted another offer.',
    },
    // More recent applications for analytics (June - October 2025)
    {
      companyName: 'WebTech Studios',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 110000,
        max: 140000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-06-15'),
      targetDate: new Date('2025-06-10'),
      tags: ['react', 'javascript', 'css'],
      notes: 'Applied through LinkedIn',
    },
    {
      companyName: 'AI Innovations',
      position: 'Full Stack Developer',
      status: 'rejected',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'San Francisco, CA',
      salary: {
        min: 140000,
        max: 180000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-07-01'),
      targetDate: new Date('2025-06-28'),
      tags: ['python', 'react', 'ai', 'ml'],
      notes: 'Rejected after initial screening - position filled internally',
    },
    {
      companyName: 'GreenTech Solutions',
      position: 'Software Engineer',
      status: 'interviewing',
      priority: 'high',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Portland, OR',
      salary: {
        min: 125000,
        max: 155000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-08-10'),
      targetDate: new Date('2025-08-05'),
      tags: ['sustainability', 'typescript', 'node'],
      notes: 'Passionate about their environmental mission',
    },
    {
      companyName: 'FinServ Tech',
      position: 'Senior Frontend Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'New York, NY',
      salary: {
        min: 145000,
        max: 175000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-08-22'),
      targetDate: new Date('2025-08-20'),
      tags: ['react', 'finance', 'typescript'],
    },
    {
      companyName: 'DevTools Inc',
      position: 'UI Developer',
      status: 'rejected',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      appliedDate: new Date('2025-09-05'),
      targetDate: new Date('2025-09-01'),
      tags: ['ui', 'css', 'design'],
      notes: 'Not a good fit for experience level',
    },
    {
      companyName: 'MediaStream Co',
      position: 'Frontend Architect',
      status: 'interviewing',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Los Angeles, CA',
      salary: {
        min: 160000,
        max: 200000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-18'),
      targetDate: new Date('2025-09-15'),
      tags: ['streaming', 'performance', 'react'],
      notes: 'Exciting opportunity in media streaming',
    },
    {
      companyName: 'EduTech Platform',
      position: 'Senior Software Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 130000,
        max: 160000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-01'),
      targetDate: new Date('2025-09-28'),
      tags: ['education', 'react', 'node'],
      notes: 'Mission-driven company focused on education',
    },
    {
      companyName: 'CyberSecure Systems',
      position: 'Full Stack Engineer',
      status: 'interviewing',
      priority: 'high',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Austin, TX',
      salary: {
        min: 135000,
        max: 170000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-08'),
      targetDate: new Date('2025-10-05'),
      tags: ['security', 'typescript', 'golang'],
      notes: 'Strong security focus - interesting tech stack',
    },
    {
      companyName: 'HealthTech Innovations',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Boston, MA',
      salary: {
        min: 125000,
        max: 150000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-15'),
      targetDate: new Date('2025-10-12'),
      tags: ['healthcare', 'react', 'hipaa'],
      notes: 'Healthcare technology - making an impact',
    },
    {
      companyName: 'GameDev Studios',
      position: 'Web Developer',
      status: 'applied',
      priority: 'low',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Seattle, WA',
      appliedDate: new Date('2025-10-20'),
      targetDate: new Date('2025-10-18'),
      tags: ['gaming', 'webgl', 'three.js'],
      notes: 'Would be cool to work in gaming',
    },
    // Additional applications for tripling count (36 more)
    {
      companyName: 'TechCorp Inc',
      position: 'Backend Developer',
      status: 'rejected',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'San Francisco, CA',
      salary: {
        min: 115000,
        max: 145000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-05-10'),
      targetDate: new Date('2025-05-08'),
      tags: ['node', 'python', 'aws'],
      notes: 'Different position at same company',
    },
    {
      companyName: 'StartupXYZ',
      position: 'DevOps Engineer',
      status: 'rejected',
      priority: 'low',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'New York, NY',
      appliedDate: new Date('2025-06-20'),
      targetDate: new Date('2025-06-18'),
      tags: ['kubernetes', 'docker', 'ci-cd'],
    },
    {
      companyName: 'BigTech Solutions',
      position: 'Software Engineer II',
      status: 'applied',
      priority: 'high',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Seattle, WA',
      salary: {
        min: 140000,
        max: 170000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-25'),
      targetDate: new Date('2025-09-22'),
      tags: ['java', 'microservices', 'azure'],
    },
    {
      companyName: 'WebTech Studios',
      position: 'UI Engineer',
      status: 'rejected',
      priority: 'low',
      workType: 'remote',
      employmentType: 'contract',
      location: 'Remote',
      appliedDate: new Date('2025-07-05'),
      targetDate: new Date('2025-07-01'),
      tags: ['css', 'design', 'react'],
      notes: 'Contract position - not interested anymore',
    },
    {
      companyName: 'CloudScale Systems',
      position: 'Platform Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Austin, TX',
      salary: {
        min: 130000,
        max: 160000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-18'),
      targetDate: new Date('2025-10-15'),
      tags: ['aws', 'terraform', 'kubernetes'],
    },
    {
      companyName: 'DataCorp Analytics',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Boston, MA',
      salary: {
        min: 120000,
        max: 150000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-08-15'),
      targetDate: new Date('2025-08-12'),
      tags: ['react', 'data-viz', 'd3'],
      notes: 'Data visualization focus',
    },
    {
      companyName: 'E-Commerce Giants',
      position: 'Senior Software Engineer',
      status: 'rejected',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'San Jose, CA',
      salary: {
        min: 160000,
        max: 200000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-07-20'),
      targetDate: new Date('2025-07-18'),
      tags: ['react', 'node', 'postgres'],
      notes: 'Position filled internally',
    },
    {
      companyName: 'FinServ Tech',
      position: 'Full Stack Developer',
      status: 'applied',
      priority: 'medium',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'New York, NY',
      appliedDate: new Date('2025-10-05'),
      targetDate: new Date('2025-10-01'),
      tags: ['angular', 'java', 'spring'],
    },
    {
      companyName: 'PropTech Ventures',
      position: 'Frontend Engineer',
      status: 'applied',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 110000,
        max: 140000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-10'),
      targetDate: new Date('2025-09-08'),
      tags: ['vue', 'typescript', 'real-estate'],
    },
    {
      companyName: 'TravelTech Co',
      position: 'Software Engineer',
      status: 'rejected',
      priority: 'medium',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Denver, CO',
      appliedDate: new Date('2025-06-10'),
      targetDate: new Date('2025-06-08'),
      tags: ['react', 'maps', 'travel'],
      notes: 'Not moving forward',
    },
    {
      companyName: 'EduTech Platform',
      position: 'Lead Frontend Developer',
      status: 'applied',
      priority: 'high',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 145000,
        max: 175000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-12'),
      targetDate: new Date('2025-10-10'),
      tags: ['react', 'leadership', 'education'],
    },
    {
      companyName: 'RoboTech Industries',
      position: 'Web Developer',
      status: 'rejected',
      priority: 'low',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Pittsburgh, PA',
      appliedDate: new Date('2025-05-25'),
      targetDate: new Date('2025-05-20'),
      tags: ['javascript', 'robotics', 'iot'],
    },
    {
      companyName: 'Fashion Forward Tech',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'low',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Los Angeles, CA',
      salary: {
        min: 115000,
        max: 145000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-20'),
      targetDate: new Date('2025-09-18'),
      tags: ['react', 'e-commerce', 'fashion'],
    },
    {
      companyName: 'AI Innovations',
      position: 'Machine Learning Engineer',
      status: 'applied',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'San Francisco, CA',
      salary: {
        min: 150000,
        max: 190000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-10'),
      targetDate: new Date('2025-10-08'),
      tags: ['python', 'ml', 'pytorch'],
      notes: 'Different role - more ML focused',
    },
    {
      companyName: 'SocialMedia Corp',
      position: 'Software Engineer',
      status: 'rejected',
      priority: 'high',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Menlo Park, CA',
      salary: {
        min: 170000,
        max: 210000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-06-01'),
      targetDate: new Date('2025-05-28'),
      tags: ['react', 'graphql', 'social'],
      notes: 'Failed system design round',
    },
    {
      companyName: 'HealthTech Innovations',
      position: 'Senior Frontend Engineer',
      status: 'applied',
      priority: 'high',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Boston, MA',
      salary: {
        min: 140000,
        max: 170000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-22'),
      targetDate: new Date('2025-10-20'),
      tags: ['react', 'healthcare', 'senior'],
    },
    {
      companyName: 'LogisticsTech',
      position: 'Full Stack Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Chicago, IL',
      salary: {
        min: 125000,
        max: 155000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-01'),
      targetDate: new Date('2025-08-28'),
      tags: ['node', 'react', 'logistics'],
    },
    {
      companyName: 'BioTech Software',
      position: 'Software Developer',
      status: 'rejected',
      priority: 'low',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'San Diego, CA',
      appliedDate: new Date('2025-07-15'),
      targetDate: new Date('2025-07-12'),
      tags: ['python', 'biotech', 'data'],
    },
    {
      companyName: 'CleanEnergy Tech',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Portland, OR',
      salary: {
        min: 120000,
        max: 145000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-08-25'),
      targetDate: new Date('2025-08-22'),
      tags: ['react', 'sustainability', 'clean-energy'],
    },
    {
      companyName: 'SportsTech United',
      position: 'Web Developer',
      status: 'rejected',
      priority: 'low',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Atlanta, GA',
      appliedDate: new Date('2025-06-15'),
      targetDate: new Date('2025-06-12'),
      tags: ['react', 'sports', 'analytics'],
    },
    {
      companyName: 'InsurTech Co',
      position: 'Senior Software Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 135000,
        max: 165000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-15'),
      targetDate: new Date('2025-09-12'),
      tags: ['typescript', 'insurance', 'react'],
    },
    {
      companyName: 'MusicStream Inc',
      position: 'Frontend Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Nashville, TN',
      salary: {
        min: 115000,
        max: 140000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-08'),
      targetDate: new Date('2025-10-05'),
      tags: ['react', 'music', 'audio'],
    },
    {
      companyName: 'RealEstate Platform',
      position: 'Software Engineer',
      status: 'rejected',
      priority: 'low',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Miami, FL',
      appliedDate: new Date('2025-05-15'),
      targetDate: new Date('2025-05-12'),
      tags: ['react', 'maps', 'real-estate'],
    },
    {
      companyName: 'AgriTech Solutions',
      position: 'Full Stack Developer',
      status: 'applied',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 110000,
        max: 135000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-08-05'),
      targetDate: new Date('2025-08-01'),
      tags: ['node', 'react', 'agriculture'],
    },
    {
      companyName: 'LegalTech Innovators',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'medium',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Washington, DC',
      salary: {
        min: 125000,
        max: 150000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-28'),
      targetDate: new Date('2025-09-25'),
      tags: ['react', 'legal', 'compliance'],
    },
    {
      companyName: 'AdTech Platform',
      position: 'Software Engineer',
      status: 'rejected',
      priority: 'medium',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'San Francisco, CA',
      appliedDate: new Date('2025-06-25'),
      targetDate: new Date('2025-06-22'),
      tags: ['react', 'advertising', 'analytics'],
    },
    {
      companyName: 'FoodDelivery Tech',
      position: 'Frontend Engineer',
      status: 'applied',
      priority: 'low',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'San Francisco, CA',
      salary: {
        min: 130000,
        max: 160000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-01'),
      targetDate: new Date('2025-09-28'),
      tags: ['react', 'maps', 'food-delivery'],
    },
    {
      companyName: 'MarketingTech Hub',
      position: 'Web Developer',
      status: 'applied',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      appliedDate: new Date('2025-08-20'),
      targetDate: new Date('2025-08-18'),
      tags: ['react', 'marketing', 'analytics'],
    },
    {
      companyName: 'AutoTech Dynamics',
      position: 'Software Engineer',
      status: 'rejected',
      priority: 'high',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Detroit, MI',
      salary: {
        min: 130000,
        max: 165000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-07-10'),
      targetDate: new Date('2025-07-08'),
      tags: ['javascript', 'automotive', 'iot'],
    },
    {
      companyName: 'PetTech Care',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 105000,
        max: 130000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-05'),
      targetDate: new Date('2025-09-01'),
      tags: ['react', 'pets', 'e-commerce'],
    },
    {
      companyName: 'NewsMedia Digital',
      position: 'Software Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'New York, NY',
      salary: {
        min: 120000,
        max: 145000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-14'),
      targetDate: new Date('2025-10-12'),
      tags: ['react', 'cms', 'news'],
    },
    {
      companyName: 'ConstructionTech',
      position: 'Full Stack Developer',
      status: 'rejected',
      priority: 'low',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Dallas, TX',
      appliedDate: new Date('2025-05-20'),
      targetDate: new Date('2025-05-18'),
      tags: ['node', 'react', 'construction'],
    },
    {
      companyName: 'AerospaceWeb',
      position: 'Software Developer',
      status: 'applied',
      priority: 'medium',
      workType: 'onsite',
      employmentType: 'full-time',
      location: 'Houston, TX',
      salary: {
        min: 125000,
        max: 155000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-08-10'),
      targetDate: new Date('2025-08-08'),
      tags: ['javascript', 'aerospace', 'data-viz'],
    },
    {
      companyName: 'RetailTech Systems',
      position: 'Frontend Engineer',
      status: 'applied',
      priority: 'medium',
      workType: 'hybrid',
      employmentType: 'full-time',
      location: 'Minneapolis, MN',
      salary: {
        min: 115000,
        max: 140000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-09-18'),
      targetDate: new Date('2025-09-15'),
      tags: ['react', 'retail', 'pos'],
    },
    {
      companyName: 'CryptoTech Exchange',
      position: 'Senior Software Engineer',
      status: 'rejected',
      priority: 'high',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 150000,
        max: 190000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-06-05'),
      targetDate: new Date('2025-06-01'),
      tags: ['typescript', 'blockchain', 'crypto'],
      notes: 'Market volatility concerns',
    },
    {
      companyName: 'HRTech Platform',
      position: 'Frontend Developer',
      status: 'applied',
      priority: 'low',
      workType: 'remote',
      employmentType: 'full-time',
      location: 'Remote',
      salary: {
        min: 110000,
        max: 135000,
        currency: 'USD',
      },
      appliedDate: new Date('2025-10-16'),
      targetDate: new Date('2025-10-14'),
      tags: ['react', 'hr', 'saas'],
    },
    {
      companyName: 'EventTech Co',
      position: 'Web Developer',
      status: 'applied',
      priority: 'low',
      workType: 'hybrid',
      employmentType: 'contract',
      location: 'Las Vegas, NV',
      appliedDate: new Date('2025-09-22'),
      targetDate: new Date('2025-09-20'),
      tags: ['javascript', 'events', 'ticketing'],
    },
  ];

  // Add applications with generated IDs and timestamps
  const applicationIds: Record<string, string> = {};
  for (const app of sampleApplications) {
    const id = generateId();
    // Store ID with a unique key combining company and position to handle multiple applications to same company
    const key = `${app.companyName}`;
    applicationIds[key] = id;
    await db.applications.add({
      ...app,
      id,
      createdAt: app.appliedDate || new Date(),
      updatedAt: new Date(),
    } as Application);
  }

  console.log(`✅ Seeded ${sampleApplications.length} sample applications`);

  // Seed Companies
  const sampleCompanies: Array<Omit<Company, 'id' | 'createdAt' | 'updatedAt'>> = [
    {
      name: 'TechCorp Inc',
      website: 'https://techcorp.com',
      industry: ['Technology', 'Software'],
      size: '1000-5000',
      location: 'San Francisco, CA',
      founded: '2010',
      remotePolicy: 'hybrid',
      description: 'Leading cloud infrastructure provider specializing in scalable web applications',
      techStack: ['React', 'TypeScript', 'AWS', 'Kubernetes'],
      researched: true,
      applicationIds: [applicationIds['TechCorp Inc']],
      ratings: {
        overall: 4.2,
        workLifeBalance: 4.0,
        compensation: 4.5,
        careerGrowth: 4.3,
      },
    },
    {
      name: 'StartupXYZ',
      website: 'https://startupxyz.com',
      industry: ['Startup', 'Fintech'],
      size: '50-200',
      location: 'New York, NY',
      founded: '2020',
      remotePolicy: 'hybrid',
      description: 'Innovative fintech startup disrupting payments with cutting-edge technology',
      techStack: ['Node.js', 'React', 'MongoDB', 'GraphQL'],
      researched: true,
      applicationIds: [applicationIds.StartupXYZ],
      ratings: {
        overall: 3.8,
        workLifeBalance: 3.5,
        compensation: 4.0,
      },
    },
    {
      name: 'BigTech Solutions',
      website: 'https://bigtech.com',
      industry: ['Technology', 'Enterprise Software'],
      size: '10000+',
      location: 'Seattle, WA',
      founded: '1998',
      remotePolicy: 'on-site',
      description: 'Global enterprise software leader with comprehensive business solutions',
      techStack: ['React', 'Redux', 'GraphQL', 'Azure'],
      researched: true,
      applicationIds: [applicationIds['BigTech Solutions']],
      ratings: {
        overall: 4.5,
        workLifeBalance: 4.2,
        compensation: 4.8,
        careerGrowth: 4.6,
      },
    },
    {
      name: 'CloudScale Systems',
      website: 'https://cloudscale.io',
      industry: ['Technology', 'Cloud Services'],
      size: '500-1000',
      location: 'Austin, TX',
      founded: '2015',
      remotePolicy: 'full-remote',
      description: 'Cloud-native platform for building and deploying microservices at scale',
      techStack: ['AWS', 'Docker', 'Kubernetes', 'Go', 'Python'],
      researched: true,
      applicationIds: [applicationIds['CloudScale Systems']],
      ratings: {
        overall: 4.1,
        workLifeBalance: 4.3,
        compensation: 4.2,
        careerGrowth: 4.0,
      },
    },
    {
      name: 'InnovateLabs',
      website: 'https://innovatelabs.com',
      industry: ['Technology', 'Design'],
      size: '200-500',
      location: 'Remote',
      founded: '2018',
      remotePolicy: 'full-remote',
      description: 'Design systems company creating beautiful, accessible user interfaces',
      techStack: ['React', 'Figma', 'Storybook', 'TypeScript', 'CSS-in-JS'],
      researched: true,
      applicationIds: [applicationIds.InnovateLabs],
      ratings: {
        overall: 4.4,
        workLifeBalance: 4.6,
        compensation: 4.1,
        careerGrowth: 4.2,
      },
    },
    {
      name: 'GreenTech Solutions',
      website: 'https://greentech-solutions.com',
      industry: ['Technology', 'Sustainability'],
      size: '200-500',
      location: 'Portland, OR',
      founded: '2019',
      remotePolicy: 'full-remote',
      description: 'Building technology solutions for environmental sustainability and climate action',
      techStack: ['TypeScript', 'Node.js', 'React', 'PostgreSQL'],
      researched: true,
      applicationIds: [applicationIds['GreenTech Solutions']],
      ratings: {
        overall: 4.0,
        workLifeBalance: 4.4,
        compensation: 3.7,
        careerGrowth: 3.9,
      },
    },
    {
      name: 'MediaStream Co',
      website: 'https://mediastream.co',
      industry: ['Technology', 'Media', 'Entertainment'],
      size: '1000-5000',
      location: 'Los Angeles, CA',
      founded: '2012',
      remotePolicy: 'hybrid',
      description: 'Leading video streaming platform delivering high-quality content globally',
      techStack: ['React', 'WebRTC', 'CDN', 'Node.js', 'FFmpeg'],
      researched: true,
      applicationIds: [applicationIds['MediaStream Co']],
      ratings: {
        overall: 4.3,
        workLifeBalance: 3.8,
        compensation: 4.6,
        careerGrowth: 4.4,
      },
    },
    {
      name: 'CyberSecure Systems',
      website: 'https://cybersecure.com',
      industry: ['Technology', 'Security'],
      size: '500-1000',
      location: 'Austin, TX',
      founded: '2016',
      remotePolicy: 'full-remote',
      description: 'Cybersecurity solutions protecting businesses from modern threats',
      techStack: ['TypeScript', 'Go', 'Rust', 'Kubernetes', 'Zero Trust'],
      researched: true,
      applicationIds: [applicationIds['CyberSecure Systems']],
      ratings: {
        overall: 4.2,
        workLifeBalance: 4.0,
        compensation: 4.4,
        careerGrowth: 4.1,
      },
    },
    {
      name: 'HealthTech Innovations',
      website: 'https://healthtech-innovations.com',
      industry: ['Technology', 'Healthcare'],
      size: '500-1000',
      location: 'Boston, MA',
      founded: '2017',
      remotePolicy: 'hybrid',
      description: 'Healthcare technology improving patient outcomes through digital solutions',
      techStack: ['React', 'HIPAA-compliant', 'FHIR', 'Node.js', 'AWS'],
      researched: false,
      applicationIds: [applicationIds['HealthTech Innovations']],
      ratings: {
        overall: 3.9,
        workLifeBalance: 4.1,
        compensation: 4.0,
      },
    },
    {
      name: 'AI Innovations',
      website: 'https://ai-innovations.com',
      industry: ['Technology', 'Artificial Intelligence'],
      size: '200-500',
      location: 'San Francisco, CA',
      founded: '2021',
      remotePolicy: 'hybrid',
      description: 'Cutting-edge AI and machine learning solutions for enterprise',
      techStack: ['Python', 'TensorFlow', 'PyTorch', 'React', 'Kubernetes'],
      researched: true,
      applicationIds: [applicationIds['AI Innovations']],
      ratings: {
        overall: 4.1,
        workLifeBalance: 3.6,
        compensation: 4.7,
        careerGrowth: 4.5,
      },
    },
    {
      name: 'EduTech Platform',
      website: 'https://edutech-platform.com',
      industry: ['Technology', 'Education'],
      size: '500-1000',
      location: 'Remote',
      founded: '2018',
      remotePolicy: 'full-remote',
      description: 'Online learning platform making education accessible to everyone',
      techStack: ['React', 'Node.js', 'MongoDB', 'WebRTC', 'LMS'],
      researched: false,
      applicationIds: [applicationIds['EduTech Platform']],
      ratings: {
        overall: 3.8,
        workLifeBalance: 4.2,
        compensation: 3.6,
      },
    },
    {
      name: 'FinServ Tech',
      website: 'https://finserv-tech.com',
      industry: ['Technology', 'Financial Services'],
      size: '1000-5000',
      location: 'New York, NY',
      founded: '2005',
      remotePolicy: 'on-site',
      description: 'Financial services technology powering modern banking',
      techStack: ['React', 'TypeScript', 'Java', 'Microservices'],
      researched: false,
      applicationIds: [applicationIds['FinServ Tech']],
      ratings: {
        overall: 3.9,
        workLifeBalance: 3.5,
        compensation: 4.5,
      },
    },
    {
      name: 'GameDev Studios',
      website: 'https://gamedev-studios.com',
      industry: ['Technology', 'Gaming'],
      size: '200-500',
      location: 'Seattle, WA',
      founded: '2014',
      remotePolicy: 'on-site',
      description: 'Game development studio creating immersive web-based gaming experiences',
      techStack: ['Three.js', 'WebGL', 'React', 'WebAssembly', 'Unity'],
      researched: false,
      applicationIds: [applicationIds['GameDev Studios']],
      ratings: {
        overall: 4.0,
        workLifeBalance: 3.4,
        compensation: 3.8,
      },
    },
  ];

  const companyIds: Record<string, string> = {};
  for (const company of sampleCompanies) {
    const id = generateId();
    companyIds[company.name] = id;
    await db.companies.add({
      ...company,
      id,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as Company);
  }

  console.log(`✅ Seeded ${sampleCompanies.length} sample companies`);

  // Seed Contacts
  const sampleContacts: Array<Omit<Contact, 'id' | 'createdAt' | 'updatedAt'>> = [
    {
      name: 'Sarah Johnson',
      companyId: companyIds['TechCorp Inc'],
      companyName: 'TechCorp Inc',
      title: 'Senior Recruiter',
      email: 'sarah.johnson@techcorp.com',
      linkedIn: 'https://linkedin.com/in/sarahjohnson',
      relationship: 'recruiter',
      notes: 'Very responsive, initial contact via LinkedIn',
    },
    {
      name: 'Michael Chen',
      companyId: companyIds['BigTech Solutions'],
      companyName: 'BigTech Solutions',
      title: 'Engineering Manager',
      email: 'michael.chen@bigtech.com',
      linkedIn: 'https://linkedin.com/in/michaelchen',
      relationship: 'hiring-manager',
      notes: 'Will be conducting technical interview',
    },
    {
      name: 'Emily Rodriguez',
      companyId: companyIds.StartupXYZ,
      companyName: 'StartupXYZ',
      title: 'Software Engineer',
      email: 'emily@startupxyz.com',
      relationship: 'referral',
      notes: 'Friend from university, provided referral',
    },
    {
      name: 'Tom Wilson',
      companyId: companyIds['GreenTech Solutions'],
      companyName: 'GreenTech Solutions',
      title: 'Engineering Manager',
      email: 'tom.wilson@greentech.com',
      linkedIn: 'https://linkedin.com/in/tomwilson',
      relationship: 'hiring-manager',
      notes: 'Passionate about environmental tech',
    },
    {
      name: 'Rachel Kim',
      companyId: companyIds['MediaStream Co'],
      companyName: 'MediaStream Co',
      title: 'Principal Engineer',
      email: 'rachel.kim@mediastream.co',
      linkedIn: 'https://linkedin.com/in/rachelkim',
      relationship: 'hiring-manager',
      notes: 'Expert in video streaming technology',
    },
    {
      name: 'Olivia Taylor',
      companyId: companyIds.InnovateLabs,
      companyName: 'InnovateLabs',
      title: 'Design Systems Lead',
      email: 'olivia.taylor@innovatelabs.com',
      linkedIn: 'https://linkedin.com/in/oliviataylor',
      relationship: 'hiring-manager',
      notes: 'Leading the design systems team',
    },
    {
      name: 'Daniel Roberts',
      companyId: companyIds['CyberSecure Systems'],
      companyName: 'CyberSecure Systems',
      title: 'Security Architect',
      email: 'daniel.roberts@cybersecure.com',
      linkedIn: 'https://linkedin.com/in/danielroberts',
      relationship: 'hiring-manager',
      notes: 'Security expert with 15+ years experience',
    },
    {
      name: 'Marcus Johnson',
      companyId: companyIds['CloudScale Systems'],
      companyName: 'CloudScale Systems',
      title: 'Staff Engineer',
      email: 'marcus.johnson@cloudscale.io',
      linkedIn: 'https://linkedin.com/in/marcusjohnson',
      relationship: 'employee',
      notes: 'Met at a tech conference last year',
    },
    {
      name: 'Jessica Wang',
      companyId: companyIds['AI Innovations'],
      companyName: 'AI Innovations',
      title: 'Technical Recruiter',
      email: 'jessica.wang@ai-innovations.com',
      relationship: 'recruiter',
      notes: 'Initial phone screen contact',
    },
    {
      name: 'Kevin Martinez',
      companyId: companyIds['MediaStream Co'],
      companyName: 'MediaStream Co',
      title: 'Senior Recruiter',
      email: 'kevin.martinez@mediastream.co',
      relationship: 'recruiter',
      notes: 'Friendly and professional recruiter',
    },
    {
      name: 'Amanda Lee',
      companyId: companyIds['CyberSecure Systems'],
      companyName: 'CyberSecure Systems',
      title: 'Engineering Manager',
      email: 'amanda.lee@cybersecure.com',
      linkedIn: 'https://linkedin.com/in/amandalee',
      relationship: 'hiring-manager',
      notes: 'Will conduct technical interview',
    },
    {
      name: 'Emma Brown',
      companyId: companyIds['GreenTech Solutions'],
      companyName: 'GreenTech Solutions',
      title: 'Talent Acquisition Specialist',
      email: 'emma.brown@greentech.com',
      relationship: 'recruiter',
      notes: 'Great communication throughout process',
    },
  ];

  for (const contact of sampleContacts) {
    await db.contacts.add({
      ...contact,
      id: generateId(),
      createdAt: new Date(),
      updatedAt: new Date(),
    } as Contact);
  }

  console.log(`✅ Seeded ${sampleContacts.length} sample contacts`);

  // Seed Interviews
  const sampleInterviews: Array<Omit<Interview, 'id' | 'createdAt' | 'updatedAt'>> = [
    // Past Interviews
    {
      applicationId: applicationIds['TechCorp Inc'],
      round: 1,
      type: 'phone-screen',
      status: 'completed',
      scheduledAt: new Date('2024-01-18'),
      duration: 30,
      interviewers: [
        {
          name: 'Sarah Johnson',
          title: 'Senior Recruiter',
        },
      ],
      result: 'passed',
      feedback: 'Great conversation, moving to technical round',
      followUpSent: true,
    },
    {
      applicationId: applicationIds['BigTech Solutions'],
      round: 1,
      type: 'video',
      status: 'completed',
      scheduledAt: new Date('2024-01-10'),
      duration: 45,
      interviewers: [
        {
          name: 'Michael Chen',
          title: 'Engineering Manager',
        },
      ],
      result: 'passed',
      feedback: 'Strong technical skills, good culture fit',
      followUpSent: true,
    },
    {
      applicationId: applicationIds['BigTech Solutions'],
      round: 2,
      type: 'technical',
      status: 'completed',
      scheduledAt: new Date('2024-01-15'),
      duration: 90,
      interviewers: [
        {
          name: 'David Park',
          title: 'Senior Engineer',
        },
        {
          name: 'Lisa Wang',
          title: 'Tech Lead',
        },
      ],
      result: 'passed',
      feedback: 'Excellent problem-solving skills, strong system design knowledge',
      followUpSent: true,
      questionsAsked: [
        'Design a scalable notification system',
        'Implement a debounce function',
        'Explain React reconciliation',
      ],
    },
    // Upcoming Interviews
    {
      applicationId: applicationIds['TechCorp Inc'],
      round: 2,
      type: 'technical',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-25T14:00:00'),
      duration: 60,
      meetingUrl: 'https://meet.google.com/abc-defg-hij',
      interviewers: [
        {
          name: 'Alex Thompson',
          title: 'Senior Software Engineer',
          linkedIn: 'https://linkedin.com/in/alexthompson',
        },
      ],
      preparationNotes: 'Review React hooks, system design, and data structures. Focus on state management patterns and performance optimization.',
      questionsToAsk: [
        'What does the team structure look like?',
        'What are the biggest technical challenges?',
        'How do you handle technical debt?',
        'What is the deployment process?',
      ],
    },
    {
      applicationId: applicationIds['TechCorp Inc'],
      round: 3,
      type: 'behavioral',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-28T10:30:00'),
      duration: 45,
      meetingUrl: 'https://zoom.us/j/123456789',
      interviewers: [
        {
          name: 'Jennifer Martinez',
          title: 'Engineering Manager',
        },
        {
          name: 'Robert Kim',
          title: 'VP of Engineering',
        },
      ],
      preparationNotes: 'Prepare STAR format stories. Focus on leadership, conflict resolution, and cross-team collaboration examples.',
      questionsToAsk: [
        'How does the team handle remote collaboration?',
        'What are the opportunities for growth and mentorship?',
        'Can you describe the company culture?',
      ],
    },
    {
      applicationId: applicationIds.StartupXYZ,
      round: 1,
      type: 'phone-screen',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-24T15:00:00'),
      duration: 30,
      interviewers: [
        {
          name: 'Rachel Green',
          title: 'Technical Recruiter',
          email: 'rachel@startupxyz.com',
        },
      ],
      preparationNotes: 'Initial screening call. Be ready to discuss background, salary expectations, and interest in fintech.',
      questionsToAsk: [
        'What are the next steps in the interview process?',
        'What does the tech stack look like?',
        'What is the team size?',
      ],
    },
    {
      applicationId: applicationIds['BigTech Solutions'],
      round: 3,
      type: 'panel',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-30T13:00:00'),
      duration: 90,
      location: 'Seattle Office, Building 5, Room 301',
      interviewers: [
        {
          name: 'Michael Chen',
          title: 'Engineering Manager',
        },
        {
          name: 'Sarah Williams',
          title: 'Product Manager',
        },
        {
          name: 'James Lee',
          title: 'Principal Engineer',
          linkedIn: 'https://linkedin.com/in/jameslee',
        },
      ],
      preparationNotes: 'Panel interview with cross-functional team. Prepare to discuss architecture decisions, product thinking, and team collaboration.',
      questionsToAsk: [
        'How do engineering and product teams collaborate?',
        'What is the release cadence?',
        'How do you balance technical excellence with shipping features?',
      ],
    },
    {
      applicationId: applicationIds.InnovateLabs,
      round: 1,
      type: 'video',
      status: 'scheduled',
      scheduledAt: new Date('2025-11-01T11:00:00'),
      duration: 60,
      meetingUrl: 'https://meet.google.com/xyz-abcd-efg',
      interviewers: [
        {
          name: 'Olivia Taylor',
          title: 'Design Systems Lead',
          linkedIn: 'https://linkedin.com/in/oliviataylor',
        },
      ],
      preparationNotes: 'Portfolio review and technical discussion about design systems. Bring examples of component libraries built.',
      questionsToAsk: [
        'How is the design system currently structured?',
        'What are the main pain points with the current system?',
        'How do you balance consistency with flexibility?',
        'What tools does the design team use?',
      ],
    },
    {
      applicationId: applicationIds['CloudScale Systems'],
      round: 1,
      type: 'technical',
      status: 'scheduled',
      scheduledAt: new Date('2025-11-05T16:00:00'),
      duration: 75,
      meetingUrl: 'https://teams.microsoft.com/l/meetup-join/19%3ameeting',
      interviewers: [
        {
          name: 'Marcus Johnson',
          title: 'Staff Engineer',
        },
      ],
      preparationNotes: 'Live coding session focused on algorithms and system design. Expect AWS and microservices questions.',
      questionsToAsk: [
        'What does the infrastructure look like?',
        'How do you handle service discovery and communication?',
        'What monitoring and observability tools do you use?',
      ],
    },
    {
      applicationId: applicationIds['TechCorp Inc'],
      round: 4,
      type: 'final',
      status: 'scheduled',
      scheduledAt: new Date('2025-11-08T14:00:00'),
      duration: 30,
      meetingUrl: 'https://meet.google.com/final-round-abc',
      interviewers: [
        {
          name: 'Patricia Anderson',
          title: 'Director of Engineering',
        },
      ],
      preparationNotes: 'Final conversation with director. Discuss vision, fit, and expectations. Be ready to ask thoughtful questions about the role.',
      questionsToAsk: [
        'What does success look like in the first 90 days?',
        'What are the biggest priorities for the team?',
        'How do you see this role evolving?',
      ],
    },
    // More interviews for recent applications
    {
      applicationId: applicationIds['GreenTech Solutions'],
      round: 1,
      type: 'phone-screen',
      status: 'completed',
      scheduledAt: new Date('2025-08-18'),
      duration: 30,
      interviewers: [
        {
          name: 'Emma Brown',
          title: 'Talent Acquisition',
        },
      ],
      result: 'passed',
      feedback: 'Great enthusiasm for sustainability mission',
      followUpSent: true,
    },
    {
      applicationId: applicationIds['GreenTech Solutions'],
      round: 2,
      type: 'technical',
      status: 'completed',
      scheduledAt: new Date('2025-09-05'),
      duration: 60,
      interviewers: [
        {
          name: 'Tom Wilson',
          title: 'Engineering Manager',
        },
      ],
      result: 'passed',
      feedback: 'Strong coding skills, good problem-solving approach',
      followUpSent: true,
      questionsAsked: [
        'Implement a binary search tree',
        'Optimize API response times',
      ],
    },
    {
      applicationId: applicationIds['GreenTech Solutions'],
      round: 3,
      type: 'behavioral',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-26T15:00:00'),
      duration: 45,
      meetingUrl: 'https://zoom.us/j/greentech-interview',
      interviewers: [
        {
          name: 'Sarah Chen',
          title: 'VP of Engineering',
        },
      ],
      preparationNotes: 'Focus on teamwork, sustainability projects, and long-term career goals',
      questionsToAsk: [
        'How does the company measure environmental impact?',
        'What are the growth opportunities?',
      ],
    },
    {
      applicationId: applicationIds['MediaStream Co'],
      round: 1,
      type: 'phone-screen',
      status: 'completed',
      scheduledAt: new Date('2025-09-25'),
      duration: 30,
      interviewers: [
        {
          name: 'Kevin Martinez',
          title: 'Senior Recruiter',
        },
      ],
      result: 'passed',
      feedback: 'Strong background in performance optimization',
      followUpSent: true,
    },
    {
      applicationId: applicationIds['MediaStream Co'],
      round: 2,
      type: 'technical',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-27T10:00:00'),
      duration: 75,
      meetingUrl: 'https://meet.google.com/mediastream-tech',
      interviewers: [
        {
          name: 'Rachel Kim',
          title: 'Principal Engineer',
        },
        {
          name: 'Mike Johnson',
          title: 'Tech Lead - Video',
        },
      ],
      preparationNotes: 'Deep dive into video streaming, CDN optimization, and React performance patterns',
      questionsToAsk: [
        'What video codecs and streaming protocols do you use?',
        'How do you handle global CDN distribution?',
        'What are the main performance challenges?',
      ],
    },
    {
      applicationId: applicationIds['CyberSecure Systems'],
      round: 1,
      type: 'video',
      status: 'completed',
      scheduledAt: new Date('2025-10-14'),
      duration: 45,
      interviewers: [
        {
          name: 'Daniel Roberts',
          title: 'Security Architect',
        },
      ],
      result: 'passed',
      feedback: 'Good understanding of security principles',
      followUpSent: true,
    },
    {
      applicationId: applicationIds['CyberSecure Systems'],
      round: 2,
      type: 'technical',
      status: 'scheduled',
      scheduledAt: new Date('2025-10-29T14:00:00'),
      duration: 90,
      meetingUrl: 'https://teams.microsoft.com/cybersecure-interview',
      interviewers: [
        {
          name: 'Amanda Lee',
          title: 'Engineering Manager',
        },
      ],
      preparationNotes: 'Security-focused coding challenge, authentication, encryption, and secure coding practices',
      questionsToAsk: [
        'What security certifications does the team hold?',
        'How do you handle security incidents?',
        'What is the security audit process?',
      ],
    },
    {
      applicationId: applicationIds['AI Innovations'],
      round: 1,
      type: 'phone-screen',
      status: 'completed',
      scheduledAt: new Date('2025-07-08'),
      duration: 30,
      interviewers: [
        {
          name: 'Jessica Wang',
          title: 'Recruiter',
        },
      ],
      result: 'failed',
      feedback: 'Not enough ML/AI experience for the role',
      followUpSent: false,
    },
    {
      applicationId: applicationIds['DevTools Inc'],
      round: 1,
      type: 'video',
      status: 'completed',
      scheduledAt: new Date('2025-09-10'),
      duration: 30,
      interviewers: [
        {
          name: 'Chris Taylor',
          title: 'Design Lead',
        },
      ],
      result: 'failed',
      feedback: 'Looking for more design-focused experience',
      followUpSent: false,
    },
  ];

  for (const interview of sampleInterviews) {
    await db.interviews.add({
      ...interview,
      id: generateId(),
      createdAt: new Date(),
      updatedAt: new Date(),
    } as Interview);
  }

  console.log(`✅ Seeded ${sampleInterviews.length} sample interviews`);

  // Seed Documents
  const baseDocumentId1 = generateId();
  const baseDocumentId2 = generateId();
  const baseDocumentId3 = generateId();
  
  const sampleDocuments: Array<Omit<Document, 'id' | 'createdAt' | 'updatedAt'>> = [
    // Resumes with version history
    {
      name: 'Software Engineer Resume',
      type: 'resume',
      version: 1,
      versionName: 'Original',
      content: 'PROFESSIONAL SUMMARY\n\nExperienced software engineer with 5+ years building web applications...\n\nSKILLS\n- JavaScript, React, Node.js\n- HTML, CSS, SQL',
      tags: ['tech', 'general'],
      notes: 'Initial resume version - too generic',
    },
    {
      name: 'Software Engineer Resume',
      type: 'resume',
      version: 2,
      versionName: 'General Tech',
      baseDocumentId: baseDocumentId1,
      content: 'PROFESSIONAL SUMMARY\n\nSoftware Engineer with 5+ years of experience building scalable web applications using modern frameworks. Strong background in React, TypeScript, and cloud architecture...\n\nSKILLS\n- Frontend: React, TypeScript, Next.js, Redux\n- Backend: Node.js, Express, PostgreSQL\n- Cloud: AWS, Docker, Kubernetes',
      tags: ['tech', 'general', 'updated'],
      notes: 'Improved with metrics and specific technologies',
      lastUsedDate: new Date('2025-01-15'),
    },
    {
      name: 'Frontend Specialist Resume',
      type: 'resume',
      version: 1,
      versionName: 'Frontend Focus v1',
      content: 'PROFESSIONAL SUMMARY\n\nFrontend specialist with deep expertise in React, TypeScript...\n\nEXPERIENCE\nSenior Frontend Developer - Current Company (2022-Present)\n- Built responsive web applications',
      tags: ['frontend', 'react'],
      notes: 'First version - needs more detail',
    },
    {
      name: 'Frontend Specialist Resume',
      type: 'resume',
      version: 2,
      versionName: 'Frontend Focus - Current',
      baseDocumentId: baseDocumentId2,
      content: 'PROFESSIONAL SUMMARY\n\nFrontend specialist with 6+ years crafting exceptional user experiences. Deep expertise in React, TypeScript, state management, and component architecture...\n\nEXPERIENCE\nSenior Frontend Developer - Current Company (2022-Present)\n- Built 15+ responsive web applications serving 100K+ users\n- Reduced initial load time by 40% through code splitting and optimization\n- Led migration from JavaScript to TypeScript across 50+ components',
      tags: ['frontend', 'react', 'senior'],
      notes: 'Enhanced with metrics and achievements',
      usedInApplicationIds: [applicationIds['TechCorp Inc'], applicationIds.InnovateLabs],
      lastUsedDate: new Date('2025-10-15'),
    },
    {
      name: 'Full Stack Resume',
      type: 'resume',
      version: 1,
      versionName: 'Full Stack v1',
      content: 'PROFESSIONAL SUMMARY\n\nVersatile full stack engineer comfortable working across the entire technology stack...\n\nSKILLS\n- Frontend: React, Vue.js, Angular\n- Backend: Node.js, Python, Java\n- Database: PostgreSQL, MongoDB, Redis\n- DevOps: Docker, CI/CD, AWS',
      tags: ['fullstack', 'backend', 'frontend'],
      notes: 'Comprehensive full stack resume',
      usedInApplicationIds: [applicationIds.StartupXYZ],
      lastUsedDate: new Date('2025-01-20'),
    },
    
    // Cover Letters with versions
    {
      name: 'TechCorp Cover Letter',
      type: 'cover-letter',
      version: 1,
      versionName: 'Draft',
      applicationId: applicationIds['TechCorp Inc'],
      content: 'Dear Hiring Manager,\n\nI am excited to apply for the Senior Frontend Developer position at TechCorp...',
      tags: ['techcorp', 'draft'],
      notes: 'Initial draft - too generic',
    },
    {
      name: 'TechCorp Cover Letter',
      type: 'cover-letter',
      version: 2,
      versionName: 'Final',
      baseDocumentId: baseDocumentId3,
      applicationId: applicationIds['TechCorp Inc'],
      content: 'Dear Sarah Johnson,\n\nI am thrilled to apply for the Senior Frontend Developer position at TechCorp. With over 5 years of experience building scalable React applications and a passion for creating exceptional user experiences, I am confident I would be a valuable addition to your team.\n\nYour focus on cloud infrastructure and modern development practices aligns perfectly with my background in AWS, TypeScript, and component-driven architecture...\n\nBest regards,\n[Your Name]',
      tags: ['techcorp', 'final'],
      notes: 'Personalized with recruiter name and company specifics',
      usedInApplicationIds: [applicationIds['TechCorp Inc']],
      lastUsedDate: new Date('2025-01-15'),
    },
    {
      name: 'StartupXYZ Cover Letter',
      type: 'cover-letter',
      version: 1,
      versionName: 'Final',
      applicationId: applicationIds.StartupXYZ,
      content: 'Dear Hiring Team,\n\nI am writing to express my strong interest in the Full Stack Engineer position at StartupXYZ. As someone passionate about fintech innovation, I am excited about the opportunity to contribute to your mission of disrupting the payments industry.\n\nMy experience with Node.js, React, and MongoDB makes me well-suited for this role...\n\nSincerely,\n[Your Name]',
      tags: ['startup', 'fintech'],
      notes: 'Tailored for startup culture and fintech focus',
      usedInApplicationIds: [applicationIds.StartupXYZ],
      lastUsedDate: new Date('2025-01-20'),
    },
    {
      name: 'BigTech Cover Letter',
      type: 'cover-letter',
      version: 1,
      versionName: 'Final',
      applicationId: applicationIds['BigTech Solutions'],
      content: 'Dear Michael Chen,\n\nI am excited to apply for the React Developer position at BigTech Solutions. With a proven track record of building enterprise-scale applications and deep expertise in React, Redux, and GraphQL, I am confident I can contribute to your team from day one.\n\nYour company\'s commitment to engineering excellence and innovation resonates with my professional values...\n\nBest regards,\n[Your Name]',
      tags: ['bigtech', 'enterprise'],
      notes: 'Emphasizes enterprise experience and scale',
      usedInApplicationIds: [applicationIds['BigTech Solutions']],
      lastUsedDate: new Date('2025-01-05'),
    },
    
    // Portfolio and other documents
    {
      name: 'Portfolio Website',
      type: 'portfolio',
      version: 1,
      versionName: 'Current',
      fileName: 'portfolio.pdf',
      fileUrl: 'https://example.com/portfolio',
      tags: ['portfolio', 'projects'],
      notes: 'Link to live portfolio website with project showcases',
      usedInApplicationIds: [
        applicationIds['TechCorp Inc'],
        applicationIds.InnovateLabs,
        applicationIds['BigTech Solutions'],
      ],
      lastUsedDate: new Date('2025-10-15'),
    },
    {
      name: 'GitHub Portfolio',
      type: 'portfolio',
      version: 1,
      fileName: 'github-projects.pdf',
      fileUrl: 'https://github.com/yourname',
      content: 'GitHub Profile\n\nOpen Source Contributions:\n- React Component Library (2.3k stars)\n- TypeScript Utilities Package (890 stars)\n- Code review participation in 50+ repositories',
      tags: ['github', 'opensource'],
      notes: 'GitHub profile with open source contributions',
      usedInApplicationIds: [
        applicationIds['TechCorp Inc'],
        applicationIds.StartupXYZ,
      ],
      lastUsedDate: new Date('2025-01-20'),
    },
    {
      name: 'AWS Solutions Architect Certificate',
      type: 'certification',
      version: 1,
      fileName: 'aws-saa-certificate.pdf',
      fileUrl: '/documents/aws-certification.pdf',
      fileSize: 245000,
      mimeType: 'application/pdf',
      tags: ['aws', 'cloud', 'certification'],
      notes: 'AWS Solutions Architect Associate certification - Valid until Dec 2026',
      usedInApplicationIds: [
        applicationIds['CloudScale Systems'],
        applicationIds['TechCorp Inc'],
      ],
      lastUsedDate: new Date('2025-01-15'),
    },
    {
      name: 'University Transcript',
      type: 'transcript',
      version: 1,
      fileName: 'official-transcript.pdf',
      fileUrl: '/documents/transcript.pdf',
      fileSize: 512000,
      mimeType: 'application/pdf',
      tags: ['education', 'official'],
      notes: 'Official transcript - BS Computer Science, GPA 3.8',
      usedInApplicationIds: [applicationIds['BigTech Solutions']],
    },
    {
      name: 'React Advanced Certification',
      type: 'certification',
      version: 1,
      fileName: 'react-advanced-cert.pdf',
      fileSize: 180000,
      mimeType: 'application/pdf',
      tags: ['react', 'frontend', 'certification'],
      notes: 'Advanced React Patterns and Performance certification',
      usedInApplicationIds: [
        applicationIds['TechCorp Inc'],
        applicationIds.InnovateLabs,
        applicationIds['BigTech Solutions'],
      ],
      lastUsedDate: new Date('2025-01-05'),
    },
    {
      name: 'References List',
      type: 'other',
      version: 1,
      fileName: 'professional-references.pdf',
      content: 'PROFESSIONAL REFERENCES\n\n1. Jane Smith - Former Manager\n   Senior Engineering Manager, Tech Company\n   jane.smith@example.com | (555) 123-4567\n\n2. Robert Johnson - Tech Lead\n   Principal Engineer, Innovation Labs\n   robert.j@example.com | (555) 234-5678\n\n3. Maria Garcia - Director of Engineering\n   VP Engineering, StartupCo\n   maria.garcia@example.com | (555) 345-6789',
      tags: ['references', 'contacts'],
      notes: 'Professional references - contacted all, confirmed availability',
      usedInApplicationIds: [applicationIds['BigTech Solutions']],
    },
    {
      name: 'Side Projects Showcase',
      type: 'portfolio',
      version: 1,
      fileName: 'side-projects.pdf',
      content: 'SIDE PROJECTS\n\n1. Task Management App\n   - Full-stack React + Node.js application\n   - 500+ active users\n   - Tech: React, TypeScript, PostgreSQL, AWS\n\n2. Open Source Component Library\n   - 2.3k GitHub stars\n   - 50+ contributors\n   - Used by 100+ projects\n\n3. Dev Tools Chrome Extension\n   - 10k+ downloads\n   - 4.5 star rating',
      tags: ['projects', 'opensource', 'portfolio'],
      notes: 'Detailed side project documentation with links and metrics',
      usedInApplicationIds: [
        applicationIds.StartupXYZ,
        applicationIds.InnovateLabs,
      ],
      lastUsedDate: new Date('2025-01-20'),
    },
    {
      name: 'Salary Research Document',
      type: 'other',
      version: 1,
      fileName: 'salary-research.pdf',
      content: 'SALARY RESEARCH NOTES\n\nSenior Frontend Developer - Bay Area\n- Average: $150k-180k\n- Top companies: $180k-220k\n- Equity typically: 0.1-0.5%\n\nSources: Levels.fyi, Glassdoor, Blind',
      tags: ['research', 'salary', 'negotiation'],
      notes: 'Compiled salary research for negotiation preparation',
    },
    {
      name: 'Technical Blog Posts',
      type: 'portfolio',
      version: 1,
      fileUrl: 'https://dev.to/yourname',
      content: 'PUBLISHED TECHNICAL CONTENT\n\n- "Advanced React Patterns" (15k views)\n- "Building Scalable Frontend Architecture" (8k views)\n- "TypeScript Best Practices" (12k views)\n- "State Management Deep Dive" (6k views)',
      tags: ['blog', 'writing', 'technical'],
      notes: 'Technical blog with combined 50k+ views',
      usedInApplicationIds: [
        applicationIds['TechCorp Inc'],
        applicationIds.InnovateLabs,
      ],
    },
    
    // Deleted/outdated documents
    {
      name: 'Old Resume 2020',
      type: 'resume',
      version: 1,
      versionName: 'Outdated',
      content: 'PROFESSIONAL SUMMARY\n\nJunior developer with 2 years experience...',
      tags: ['old', 'outdated'],
      notes: 'Outdated resume from 2020 - no longer relevant',
      deletedAt: new Date('2024-12-01'),
    },
    {
      name: 'Generic Cover Letter',
      type: 'cover-letter',
      version: 1,
      versionName: 'Template',
      content: 'To Whom It May Concern,\n\nI am writing to apply for the position...',
      tags: ['generic', 'template'],
      notes: 'Too generic - replaced with customized versions',
      deletedAt: new Date('2024-11-15'),
    },
    {
      name: 'Incomplete Project Portfolio',
      type: 'portfolio',
      version: 1,
      fileName: 'old-portfolio.pdf',
      tags: ['incomplete', 'draft'],
      notes: 'Draft portfolio that was never completed',
      deletedAt: new Date('2025-01-10'),
    },
    {
      name: 'DataDriven Cover Letter Draft',
      type: 'cover-letter',
      version: 1,
      applicationId: applicationIds['DataDriven Co'],
      content: 'Dear Hiring Manager,\n\nI am interested in the Frontend Architect position...',
      tags: ['draft', 'datadriven'],
      notes: 'Deleted after receiving rejection - no longer needed',
      deletedAt: new Date('2024-01-12'),
    },
    {
      name: 'Expired Security Clearance',
      type: 'certification',
      version: 1,
      fileName: 'security-clearance.pdf',
      tags: ['clearance', 'expired'],
      notes: 'Security clearance expired in 2023 - keeping for reference',
      deletedAt: new Date('2024-10-01'),
    },
    {
      name: 'Old Portfolio Website 2021',
      type: 'portfolio',
      version: 1,
      fileUrl: 'https://old-portfolio.example.com',
      tags: ['outdated', 'portfolio'],
      notes: 'Old portfolio site - replaced with new design',
      deletedAt: new Date('2024-11-20'),
    },
    {
      name: 'Undergraduate Transcript',
      type: 'transcript',
      version: 1,
      fileName: 'undergrad-transcript.pdf',
      tags: ['education', 'old'],
      notes: 'Replaced with official transcript that includes graduate work',
      deletedAt: new Date('2025-09-15'),
    },
    {
      name: 'Old References 2022',
      type: 'other',
      version: 1,
      content: 'OLD REFERENCES\n\n1. John Doe - Former colleague (contact lost)\n2. Sarah Wilson - Moved to different company',
      tags: ['references', 'outdated'],
      notes: 'Outdated reference list - contacts no longer valid',
      deletedAt: new Date('2024-12-20'),
    },
  ];

  // Add documents and track IDs for version history
  const documentIdMap = new Map<string, string>();
  
  for (const document of sampleDocuments) {
    let docId: string;
    
    // For base documents (version 1 without baseDocumentId), use the pre-generated IDs
    if (document.version === 1 && !document.baseDocumentId) {
      if (document.name === 'Software Engineer Resume') {
        docId = baseDocumentId1;
      } else if (document.name === 'Frontend Specialist Resume' && !documentIdMap.has('Frontend Specialist Resume-v1')) {
        docId = baseDocumentId2;
      } else if (document.name === 'TechCorp Cover Letter' && !documentIdMap.has('TechCorp Cover Letter-v1')) {
        docId = baseDocumentId3;
      } else {
        docId = generateId();
      }
      documentIdMap.set(`${document.name}-v${document.version}`, docId);
    } else {
      docId = generateId();
    }
    
    await db.documents.add({
      ...document,
      id: docId,
      createdAt: document.version === 1 
        ? new Date('2024-11-01') // Older creation date for v1
        : new Date('2025-01-15'), // Newer date for v2+
      updatedAt: document.deletedAt 
        ? document.deletedAt 
        : new Date(),
    } as Document);
  }

  console.log(`✅ Seeded ${sampleDocuments.length} sample documents (including ${sampleDocuments.filter(d => d.deletedAt).length} deleted)`);
  console.log('🎉 Database fully seeded with demo data!');
}

// Export a function to clear the database
export async function clearDatabase() {
  await db.applications.clear();
  await db.companies.clear();
  await db.contacts.clear();
  await db.interviews.clear();
  await db.documents.clear();
  console.log('✅ Database cleared');
}
